### ISSUE TITLE
Adding content_type causes changeset invalid

### ISSUE THREAD

**Issue by loongmxbt** [keichan34/exfile#38]
In seed.exs

```
** (Ecto.InvalidChangesetError) could not perform insert because changeset is invalid.

* Changeset changes

%{file: %Exfile.LocalFile{io: nil, meta: %{"content_type" => "image/jpeg"}, path: "/Users/loongmxbt/Github/phoenix/confer/uploads/store/ac75fa279a75e03456d4e4863391d91062b4064519e14242700c1e053946"}, title: "热力学第一定律管理员", topic_id: 1, user_id: 1}

* Changeset params

%{"file" => %Exfile.File{backend: %Exfile.Backend{backend_mod: Exfile.Backend.FileSystem, backend_name: "store", directory: "/Users/loongmxbt/Github/phoenix/confer/uploads/store", hasher: Exfile.Hasher.Random, max_size: -1, meta: %{ttl: :infinity}, postprocessors: [], preprocessors: []}, backend_meta: %{absolute_path: "/Users/loongmxbt/Github/phoenix/confer/uploads/store/078f26c817bb82e768bb853f3e242a360cc834583c65d09a768176c9fea1"}, id: "078f26c817bb82e768bb853f3e242a360cc834583c65d09a768176c9fea1", meta: %{}}, "title" => "111title111", "topic_id" => 1, "user_id" => 1}
```

In web app

```
[error] #PID<0.464.0> running Confer.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /papers
** (exit) an exception was raised:
    ** (Ecto.ChangeError) value `%Exfile.LocalFile{io: nil, meta: %{"content_type" => "application/pdf"}, path: "/Users/loongmxbt/Github/phoenix/confer/uploads/store/2f9efa897c9bdf26722997d97e9265cae06e5ab3a553ec8c5d0c2272b927"}` for `Confer.Paper.file` in `insert` does not match type Exfile.Ecto.File
```

```
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :file, :topic_id, :user_id])
    |> validate_required([:title, :topic_id, :file, :user_id])
    |> validate_content_type(:file ,~w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document))
  end
```

How to smoothly migrate to new Exfile.Ecto using validate_content_type? Thanks al lot!

**Comment by keichan34** [comment]
Can you try again on master? I've merged a fix that should solve this issue.

**Comment by loongmxbt** [comment]
There seems still some problems in my app. I update exfile via command `mix deps.update exfile`

```
{:exfile, github: "keichan34/exfile"}
```

Is it up-to-date with master branch? And run `mix phoenix.server`, it shows an error:

```
[info] Application exfile exited: Exfile.start(:normal, []) returned an error: an exception was raised:
    ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
        (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
        (elixir) lib/enum.ex:116: Enumerable.reduce/3
        (elixir) lib/enum.ex:1636: Enum.reduce/3
        (elixir) lib/enum.ex:1188: Enum.map/2
        (elixir) lib/supervisor/spec.ex:169: Supervisor.Spec.supervise/2
        (stdlib) supervisor.erl:294: :supervisor.init/1
        (stdlib) gen_server.erl:328: :gen_server.init_it/6
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

```
** (Mix) Could not start application exfile: Exfile.start(:normal, []) returned an error: an exception was raised:
    ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
        (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
        (elixir) lib/enum.ex:116: Enumerable.reduce/3
        (elixir) lib/enum.ex:1636: Enum.reduce/3
        (elixir) lib/enum.ex:1188: Enum.map/2
        (elixir) lib/supervisor/spec.ex:169: Supervisor.Spec.supervise/2
        (stdlib) supervisor.erl:294: :supervisor.init/1
        (stdlib) gen_server.erl:328: :gen_server.init_it/6
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

Everything can run with last master branch, but has the mentioned bug. I'm really new to exfile, hoping help, thanks!

**Comment by keichan34** [comment]
Oh, I'm terribly sorry -- there was a bug in a commit I made that prevented non-test environments from booting, displaying that error message. If you run `mix deps.update exfile` now and try again, it should work.. Let me know if you're having any other problems.

**Comment by loongmxbt** [comment]
The new github version fixed it! Still have something strange in `cast_filename` feature, but in another issue. Really helps a lot!
